name: ARM Linux Simulation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  simulate-arm-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create Docker Buildx Builder
      run: docker buildx create --name mybuilder

    - name: Build Empty ARM64 Image
      run: docker buildx build --platform linux/arm64 -t empty-arm64 --load .
    
    - name: Run command in ARM64 container
      run: docker run --rm empty-arm64 ls -l
