name: Run GoTest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ARM64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test ARM64
        uses: docker/build-push-action@v5
        with:
          context: {{defaultContext}}:dev
          file: ./dev/dockerfile-arm64-github-actions
          platforms: linux/arm64
          push: false
          tags: ghcr.io/langgenius/dify-sandbox:arm64-test
