name: Run GoTest

on:
  pull_request:
    branches:
      - main

concurrency:
  group: test-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Install dependencies
        run: go mod tidy

      - name: Run Intgeration tests
        run: go test -v github.com/langgenius/dify-sandbox/tests/integration_tests/...
